# Generated by Django 4.2.2 on 2023-08-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del bloque')),
                ('funciones', models.CharField(max_length=100, verbose_name='Funciones del Bloque')),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, verbose_name='Nombre del encargado')),
                ('numero_planta', models.IntegerField(verbose_name='Número de plantas')),
                ('horario_bloque', models.CharField(max_length=100, verbose_name='Horarios')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, verbose_name='iframe')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloque_imagenes/')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_planta', models.IntegerField(verbose_name='Número de planta')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='sitios.bloque')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Sitio')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Horario de atencion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloque_imagenes/')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Sitio')),
                ('aulas', models.TextField(blank=True, null=True)),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Encargado')),
                ('bloque', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='sitios.bloque')),
                ('planta', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sitios.planta')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
            },
        ),
    ]
