# Generated by Django 4.2.2 on 2023-07-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_alter_bloque_nombre_encargado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='foto',
            field=models.URLField(blank=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='horario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario de atencion'),
        ),
    ]
