# Generated by Django 4.2.2 on 2023-07-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0003_alter_sitio_foto_alter_sitio_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='gps',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
