# Generated by Django 4.2.2 on 2023-07-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0004_alter_sitio_gps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='Bloques',
            new_name='bloque',
        ),
    ]
