# Generated by Django 4.2.2 on 2023-07-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0005_rename_bloques_sitio_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='gps',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
