# Generated by Django 4.2.2 on 2023-07-23 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0006_bloque_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_planta', models.IntegerField(verbose_name='Número de planta')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='sitios.bloque')),
            ],
        ),
        migrations.AddField(
            model_name='sitio',
            name='planta',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.planta'),
        ),
    ]
