# Generated by Django 4.2.2 on 2023-07-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0007_planta_sitio_planta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'verbose_name': 'Planta', 'verbose_name_plural': 'Plantas'},
        ),
    ]
