# Generated by Django 4.2.2 on 2023-07-27 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sitios", "0008_alter_planta_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloque",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="bloque_imagenes/"
            ),
        ),
        migrations.AlterField(
            model_name="bloque",
            name="numero_planta",
            field=models.IntegerField(verbose_name="Número de plantas"),
        ),
        migrations.AlterField(
            model_name="sitio",
            name="planta",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sitios.planta",
            ),
        ),
    ]
